services:
  guardian:
    build:
      context: .
      dockerfile: Dockerfile
    cap_add:
      - IPC_LOCK
    hostname: guardian-0
    ports:
      - "7070:7070"
      - "7071:7071"
    command:
      - ./wait-for-it.sh
      - -t
      - "0"
      - eth1-deploy:2000
      - --
      - ./wait-for-it.sh
      - -t
      - "0"
      - eth2-deploy:2000
      - --
      - /guardiand
      - node
      - --ethRPC
      - ws://eth1:8545
      - --bscRPC
      - ws://eth2:8546
      - --polygonRPC
      - ws://eth1:8545
      - --avalancheRPC
      - ws://eth1:8545
      - --terraWS
      - ws://terra-terrad:26657/websocket
      - --terraLCD
      - http://terra-lcd:1317
      - --terraContract
      - terra18vd8fpwxzck93qlwghaj6arh4p7c5n896xzem5
      - --solanaContract
      - Bridge1p5gheXUvJ6jGWGeCsgPKgnE3YgdGKRVCMY9o
      - --solanaWS
      - ws://solana-devnet:8900
      - --solanaRPC
      - http://solana-devnet:8899
      - --unsafeDevMode
      - --guardianKey
      - /tmp/bridge.key
      - --publicRPC
      - "[::]:7070"
      - --publicWeb
      - "[::]:7071"
      - --adminSocket
      - /tmp/admin.sock
      - --dataDir
      - /tmp/data
    depends_on:
      - eth1
      - eth2
  eth1:
    build:
      context: .
      dockerfile: Dockerfile.eth
    ports:
      - "8545:8545"
    command:
      - npx
      - ganache-cli
      - -e 10000
      - --deterministic
      - --time="1970-01-01T00:00:00+00:00"
      - --host=0.0.0.0
  eth1-deploy:
    build:
      context: .
      dockerfile: Dockerfile.eth
    command:
      - /bin/sh
      - -c
      - "./wait-for-it.sh -t 0 eth1:8545 -- mkdir -p build/contracts && cp node_modules/@openzeppelin/contracts/build/contracts/* build/contracts/ && npx truffle migrate && npx truffle exec scripts/deploy_test_token.js && npx truffle exec scripts/register_bsc_chain.js && nc -lkp 2000 0.0.0.0"
    depends_on:
      - eth1
  eth1-mine:
    build:
      context: .
      dockerfile: Dockerfile.eth
    command:
      - /bin/sh
      - -c
      - "npx truffle exec mine.js"
    depends_on:
      - eth1
  eth2:
    build:
      context: .
      dockerfile: Dockerfile.eth
    ports:
      - "8546:8546"
    command:
      - npx
      - ganache-cli
      - -e 10000
      - --deterministic
      - --time="1970-01-01T00:00:00+00:00"
      - --host=0.0.0.0
      - --chainId=1397
      - --port=8546
  eth2-deploy:
    build:
      context: .
      dockerfile: Dockerfile.eth
    command:
      - /bin/sh
      - -c
      - "./wait-for-it.sh -t 0 eth2:8546 -- sed -i 's/CHAIN_ID=0x2/CHAIN_ID=0x4/g' .env && mkdir -p build/contracts && cp node_modules/@openzeppelin/contracts/build/contracts/* build/contracts/ && npx truffle migrate --network development2 && npx truffle exec scripts/deploy_test_token.js --network development2 && npx truffle exec scripts/register_eth_chain.js --network development2 && nc -lkp 2000 0.0.0.0"
    depends_on:
      - eth2
  eth2-mine:
    build:
      context: .
      dockerfile: Dockerfile.eth
    command:
      - /bin/sh
      - -c
      - "npx truffle exec mine.js --network development2"
    depends_on:
      - eth2
  solana-devnet:
    build:
      context: .
      dockerfile: Dockerfile.solana
    profiles:
      - solana
    ports:
      - "1027:1027/udp"
      - "8899:8899"
      - "8900:8900"
      - "9900:9900"
    command:
      - /root/.local/share/solana/install/active_release/bin/solana-test-validator
      - --bpf-program
      - Bridge1p5gheXUvJ6jGWGeCsgPKgnE3YgdGKRVCMY9o
      - /opt/solana/deps/bridge.so
      - --bpf-program
      - B6RHG3mfcckmrYN1UhmJzyS1XX3fZKbkeUcpJe9Sy3FE
      - /opt/solana/deps/token_bridge.so
      - --bpf-program
      - NFTWqJR8YnRVqPDvTJrYuLrQDitTG5AScqbeghi4zSA
      - /opt/solana/deps/nft_bridge.so
      - --bpf-program
      - CP1co2QMMoDPbsmV7PGcUTLFwyhgCgTXt25gLQ5LewE1
      - /opt/solana/deps/cpi_poster.so
      - --bpf-program
      - metaqbxxUerdq28cj1RbAWkYQm3ybzjb6a8bt518x1s
      - /opt/solana/deps/spl_token_metadata.so
      - --bpf-program
      - gMYYig2utAxVoXnM9UhtTWrt8e7x2SVBZqsWZJeT5Gw # Derived from pyth_program.json
      - /opt/solana/deps/pyth_oracle.so
      - --bpf-program
      - P2WH424242424242424242424242424242424242424
      - /opt/solana/deps/pyth2wormhole.so
      - --bpf-program
      - Ex9bCdVMSfx7EzB3pgSi2R4UHwJAXvTw18rBQm5YQ8gK
      - /opt/solana/deps/wormhole_migration.so
      - --log
  solana-setup:
    build:
      context: .
      dockerfile: Dockerfile.client
    profiles:
      - solana
    command:
      - /bin/sh
      - -c
      - "wget https://raw.githubusercontent.com/vishnubob/wait-for-it/master/wait-for-it.sh && chmod +x wait-for-it.sh && ./wait-for-it.sh -t 0 solana-devnet:8899 -- /usr/src/solana/devnet_setup.sh"
